Initial implementation of Web Payments feature
Igalia/wolvic-chromium pull request #143
Opened 2024-12-04 22:38 UTC by javifernandez

This PR provides a very basic implementation of the Payment Request API and the minimum viable logic for the Payment Handlers. 

In the latter case, it provides support just to launch a new tab that loads a service worker provided by the payment request. 

A new modal window will be launched to load the service worker. This window is controlled by the WolvicPaymentUiService class, which will handle the service-worker result of the generate the payment request response. 

A new ServiceTabLauncher class is implemented in Wolvic in order to launch this kind of modal dialogs.

Finally, this PR adds a new method in the WebContentsObserver to notify Wolvic when the new payment-handler WebContent instance is ready to be loaded in the modal window.

2024-12-05 01:57 UTC, mshin-wolvic approved these changes

2025-01-13 08:46 UTC, svillar requested changes

2025-01-13 08:46 UTC, svillar commented on wolvic/wolvic_permission_manager.cc
> +  }
Hmm I think we should still ask for this permission anyway

2025-01-13 09:42 UTC, javifernandez commented on wolvic/wolvic_permission_manager.cc
> +  }
We can, I guess, but bear in mind that Chrome Desktop doesn't do it.

2025-01-13 23:31 UTC, javifernandez commented on wolvic/wolvic_permission_manager.cc
> +  }
As a matter of fact, the Chromium code that handles the web payment method manifest downloading expect the permission to be GRANTED by default. I don't think we can ask the user about this.

2025-01-20 01:21 UTC, ns-mshin approved these changes

2025-01-20 01:22 UTC, mshin-wolvic approved these changes

2025-01-21 05:19 UTC, ns-mshin approved these changes
LGTM

2025-01-21 05:20 UTC, mshin-wolvic approved these changes

2025-02-05 10:11 UTC, svillar approved these changes
I still have doubts that the desktop approach is the best for our case. Using an intent as Chrome Android seems cleaner but I guess we can revisit that in the future.

2025-02-05 10:11 UTC, merged