Introduce skippable navigation entries
Igalia/wolvic-chromium pull request #76
Opened 2024-02-29 07:41 UTC by zakharvoit

Allow browser to mark navigation entries as 'skippable' so that they are not used when performing back/forward navigation. This allows us to fix navigation issues caused by YouTube redirects to desktop app.

This change also fixes a crash which happened when rapidly clicking back/forward button multiple times by ensuring that any navigation doesn't go out of bounds.

2024-02-29 09:57 UTC, mshin-wolvic commented
I wonder if we can use `canGoBack()` before accessing `goBack()` to prevent CHECK crash.

2024-02-29 11:28 UTC, zakharvoit commented
> I wonder if we can use `canGoBack()` before accessing `goBack()` to prevent CHECK crash.

Yes, it was my idea originally. But since I replaced goBack() with goToOffset() it's not needed anymore. The canGoToOffset() check is performed inside findBackForwardNavigationOffset().

2024-02-29 11:57 UTC, mshin-wolvic approved these changes

2024-02-29 13:26 UTC, svillar requested changes
I think it's a good idea. WebLayer implements something similar but in their case they have a method that the client will implement to return whether an entry should be skippable or not. I think for our use case your solution is indeed simpler. I just have a couple of suggestions.

2024-02-29 13:26 UTC, svillar commented on wolvic/java/org/chromium/wolvic/Tab.java
> +        if (mNavigationController != null) {
I don't see how navigation controller could be null unless the webcontents return null. As far as I've seen, the Chromium code assumes it is never null (although it lacks `@NonNull` annotations). Have you found code paths where the navigation controller is null? If not I prefer to remove the null check because it can give the false idea that it's a valid value.

2024-02-29 13:26 UTC, svillar commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    private int findBackForwardNavigationOffset(boolean goBack) {
I know it's an internal API but I'd prefer to use an enum here because it's much more descriptive in the call sites. Something like `enum NavigationDirection { BACK, FORWARD }` or similar.

2024-03-01 02:09 UTC, zakharvoit commented on wolvic/java/org/chromium/wolvic/Tab.java
> +        if (mNavigationController != null) {
It seems that you're right, I removed the null checks.

2024-03-01 02:09 UTC, zakharvoit commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    private int findBackForwardNavigationOffset(boolean goBack) {
Fixed.

2024-03-01 08:58 UTC, svillar approved these changes
Now it LGTM

2024-03-01 08:58 UTC, merged