Open the new window with WebContents instead of initial url
Igalia/wolvic-chromium pull request #93
Opened 2024-04-09 08:22 UTC by mshin-wolvic

This patch changes the opening window's parameter as WebContents instead of initial url so that keeps the connection of a parent window and a child window(=the popup). Also the patch changes a management of WebContents lifecycle to fix the leakage of it.

2024-04-09 18:00 UTC, svillar requested changes
This is great, I just have some minor comments.

2024-04-09 18:00 UTC, svillar commented on wolvic/browser/wolvic_web_contents_delegate.cc
> +  return false;
This is awesome. That's indeed what I wanted to do when I implemented the current solution.

2024-04-09 18:00 UTC, svillar commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    }
I am not sure about these two names, I'll explain it in the next comment

2024-04-09 18:00 UTC, svillar commented on wolvic/java/org/chromium/wolvic/Tab.java
> +            setWebContents(mWebContents);
This is the reason why I dislike `setWebContents`. Typically a setter does precisely what the previous line does, i.e. assign some object to an attribute. I think we should use a more descriptive name, perhaps `registerWolvicContents` although I don't like it too much either. Perhaps you are aware of a better naming for this kind of things in Chromium.

2024-04-09 18:00 UTC, svillar commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    }
Several `;;` in this method.

2024-04-11 03:06 UTC, mshin-wolvic commented on wolvic/java/org/chromium/wolvic/Tab.java
> +            setWebContents(mWebContents);
I renamed them that is a little more meaningful.  Thank you for giving me the chance to rethink the name.

2024-04-11 03:06 UTC, mshin-wolvic commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    }
Done

2024-04-11 03:07 UTC, mshin-wolvic commented on wolvic/java/org/chromium/wolvic/Tab.java
> +    }
Done. Please review the new name.

2024-04-11 12:00 UTC, svillar approved these changes
Great! Let's merge this

2024-04-11 12:00 UTC, merged